# Generated by Django 5.1.1 on 2024-09-22 16:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Categories', '0001_initial'),
        ('Product', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='Categories',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Categories.categories'),
        ),
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(default=1, upload_to='products/images'),
        ),
    ]
