# Generated by Django 5.1.1 on 2024-09-23 03:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0002_product_categories_product_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='Categories',
            new_name='categories',
        ),
    ]
