# Generated by Django 5.1.1 on 2024-09-23 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Categories', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='categories',
            name='image',
            field=models.ImageField(default=1, upload_to='products/images'),
        ),
    ]
