# Generated by Django 5.1.1 on 2024-09-23 06:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='home',
            old_name='title',
            new_name='name',
        ),
    ]
