# Generated by Django 5.1.1 on 2024-09-23 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0002_rename_title_home_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='home',
            name='image',
            field=models.ImageField(blank=True, default='home/images/default.jpg', null=True, upload_to='home/images'),
        ),
    ]
