# Generated by Django 5.1.1 on 2024-09-23 07:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('About', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='about',
            old_name='title',
            new_name='name',
        ),
    ]
