# Generated by Django 5.1.1 on 2024-09-23 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('About', '0002_rename_title_about_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='image',
            field=models.ImageField(default=1, upload_to='abouts/images'),
        ),
    ]
